### PR TITLE
Added method to hide Confirm button.

### PR DESCRIPTION
**Pull request by Sanjeet990**

### CODE REVIEW

**Comment by F0RIS** [comment]
This feature is already implemented here https://github.com/F0RIS/sweet-alert-dialog

**Comment by thomper** [comment]
Thanks for the work, @Sanjeet990.  I've merged this with only a cursory glance as I'm not actively maintaining this repo, it was just an easy way to continue to use Pedant's original project.

To use this with jitpack, you'll want to change the tag in your dependencies to SNAPSHOT.  I'm in agreement with @F0RIS though, you should probably switch to their better maintained fork.  Thanks for commenting here to let us know, @F0RIS.

**Comment by A7YL8ZZ** [comment]
Thanks @thomper and @F0RIS :)

**Comment by Sanjeet990** [comment]
Thanks @thomper and @F0RIS :)

**Pull request merged**
